# Generated by Django 5.2.8 on 2025-11-28 08:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0004_remove_producto_imagen_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Número de Pedido')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(help_text='Para enviar confirmación y actualizaciones del pedido', max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, help_text='Para contacto rápido (opcional)', max_length=17, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección de envío')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('notas', models.TextField(blank=True, help_text='Instrucciones especiales de entrega', verbose_name='Notas adicionales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=300, verbose_name='Producto')),
                ('presentacion_nombre', models.CharField(max_length=100, verbose_name='Presentación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('presentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.presentacion', verbose_name='Presentación')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
    ]
