# Generated by Django 5.2.8 on 2025-11-28 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=200, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URL (se genera automáticamente)', max_length=200, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la categoría está visible en la tienda', verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = mayor prioridad)', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URL (se genera automáticamente)', max_length=200, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('descripcion_corta', models.CharField(blank=True, help_text='Descripción breve para mostrar en listados', max_length=300, verbose_name='Descripción corta')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta del producto', max_digits=10, verbose_name='Precio')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento (dejar vacío si no hay oferta)', max_digits=10, null=True, verbose_name='Precio de oferta')),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/', verbose_name='Imagen principal')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Stock')),
                ('sku', models.CharField(blank=True, help_text='Código único de identificación del producto', max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está disponible para venta', verbose_name='Activo')),
                ('destacado', models.BooleanField(default=False, help_text='Indica si el producto aparece en la sección de destacados', verbose_name='Destacado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, help_text='Título descriptivo de la imagen', max_length=200, verbose_name='Título')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='catalogo_pr_slug_17e2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='catalogo_pr_categor_8a569f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'destacado'], name='catalogo_pr_activo_c84eea_idx'),
        ),
    ]
