# Generated by Django 5.2.8 on 2025-11-28 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la marca', max_length=200, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URL (se genera automáticamente)', max_length=200, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la marca', null=True, upload_to='marcas/', verbose_name='Logo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la marca', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la marca está visible en la tienda', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion_corta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_oferta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo o referencia del producto', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='Marca del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.marca', verbose_name='Marca'),
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la presentación (ej: 100ml, 30cm, Pack de 3)', max_length=100, verbose_name='Presentación')),
                ('sku', models.CharField(blank=True, help_text='Código único de identificación', max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta', max_digits=10, verbose_name='Precio')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento (dejar vacío si no hay oferta)', max_digits=10, null=True, verbose_name='Precio de oferta')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen específica de esta presentación (opcional)', null=True, upload_to='productos/presentaciones/', verbose_name='Imagen')),
                ('caracteristicas', models.TextField(blank=True, help_text='Características específicas de esta presentación', verbose_name='Características')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la presentación está disponible para venta', verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='catalogo.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('producto', 'nombre')},
            },
        ),
    ]
