# Generated by Django 5.2.8 on 2025-11-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_marca_remove_producto_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['-es_principal', 'orden'], 'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de productos'},
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Marcar como imagen principal del producto (se mostrará en listados)', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización en la galería', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título descriptivo de la imagen (ej: Vista frontal, Detalle, etc.)', max_length=200, verbose_name='Título'),
        ),
    ]
