# Generated by Django 5.2.8 on 2025-11-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_imagenproducto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_principal',
        ),
    ]
