# Generated by Django 5.2.8 on 2025-12-01 08:50

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_producto_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='mostrar_en_descripcion',
            field=models.BooleanField(default=False, help_text='Mostrar esta imagen en la sección de descripción detallada', verbose_name='Mostrar en descripción'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='mostrar_en_galeria',
            field=models.BooleanField(default=True, help_text='Mostrar esta imagen en la galería principal del producto', verbose_name='Mostrar en galería'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_corta',
            field=models.TextField(blank=True, help_text='Descripción breve del producto (máx. 500 caracteres). Se muestra junto a la imagen principal.', max_length=500, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripción completa del producto con formato. Se muestra en la sección inferior.', verbose_name='Descripción detallada'),
        ),
        migrations.CreateModel(
            name='EspecificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la especificación (ej: Potencia, Voltaje, Dimensiones)', max_length=100, verbose_name='Especificación')),
                ('valor', models.CharField(help_text='Valor de la especificación (ej: 110 GPH, 110V, 20x15x25 cm)', max_length=200, verbose_name='Valor')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización en la tabla de especificaciones', verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='catalogo.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Especificación técnica',
                'verbose_name_plural': 'Especificaciones técnicas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VideoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del video', max_length=200, verbose_name='Título')),
                ('url_youtube', models.URLField(help_text='URL completa del video de YouTube (ej: https://www.youtube.com/watch?v=xxxxx)', validators=[django.core.validators.URLValidator()], verbose_name='URL de YouTube')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalogo.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Video de producto',
                'verbose_name_plural': 'Videos de productos',
                'ordering': ['orden'],
            },
        ),
    ]
