# Generated by Django 5.2.8 on 2025-12-02 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_imagenproducto_mostrar_en_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, help_text='Categoría padre para crear subcategorías (dejar vacío si es categoría principal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalogo.categoria', verbose_name='Categoría padre'),
        ),
    ]
